name: prochain
description: "Aplikasi ProChain"
 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Package Style
  cupertino_icons: ^1.0.8
  responsive_grid: ^2.4.4
  shimmer: ^3.0.0
  timeline_tile: ^2.0.0
  loading_overlay: ^0.4.2
  introduction_screen: ^3.1.14
  flutter_spinkit: ^5.2.1
  timer_builder: ^2.0.0
  percent_indicator: ^4.2.4
  fluttertoast: ^8.2.10
  photo_view: ^0.15.0
  cached_network_image: ^3.4.1
  dotted_line: ^3.2.3

  # Package Main
  get: ^4.6.6

  # Package API
  http: ^1.2.2
  dio: ^5.7.0

  # Package Google/Firebase
  google_fonts: ^6.2.1
  # flutter_local_notifications: ^18.0.1
  # firebase_messaging: ^15.1.6
  # firebase_core: ^3.9.0
  # overlay_support: ^2.1.0

  # Package Storage
  get_storage: ^2.1.1
  shared_preferences: ^2.3.4

  # Package Format
  intl: ^0.20.1
  path_provider: ^2.1.5

  # Package Picker
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9

  # Package Others
  device_info_plus: ^11.2.0
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.14.2
  fl_chart: ^0.70.2

# Override Depedencies
dependency_overrides:
  ffi: ^2.1.3

# Config Flutter Icon (Mobile)
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/launcher/launcher.png"
  image_path_ios: "assets/launcher/launcher.png"
  adaptive_icon_foreground: "assets/launcher/launcher.png"
  adaptive_icon_background: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Asset Folder
  assets:
    - assets/json/
    - assets/background/
    - assets/example/
    - assets/icon/
    - assets/launcher/
    - assets/logo/
    - assets/message/
  
  # Asset Font
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
